### ISSUE TITLE
[Gimlet Installer] – Support Github Organizations

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/gimlet#170]
Thanks again for the awesome Tooling. 👍 

Currently its not possible for me to use the Gimlet Installer with my GitHub Organization as it only shows my personal account. 
Could be a minor fix be passing a Param to the GitHub App creation flow!?

**Comment by laszlocph** [comment]
This makes sense, let me try it!

**Comment by appinteractive** [comment]
There is a Native select where you can select your account or grand access in GitHub as far as I remember.

**Comment by laszlocph** [comment]
https://github.com/gimlet-io/gimlet/releases/tag/installer-v0.3.11
