### ISSUE TITLE
Fleet update of charts

### ISSUE THREAD

**Issue by madss** [gimlet-io/gimlet#266]
It is a bit cumbersome to manually keep the charts up-to-date in all repositories.

I would be a great addition if
- you could navigate to a repo on gimlet, and gimlet sees it is not the latest (or configured) version of the chart, you can create a PR with one click
- If that works out, there could be an overview page and you could bulk create PRs
- or even automated PRs whenever there is a new version

**Comment by laszlocph** [comment]
We shipped automated PRs #493
