### ISSUE TITLE
Copy button doesn't work in user api key copy

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet#281]
![image](https://user-images.githubusercontent.com/4289031/189112324-3f3fcf6c-c8b8-43eb-8ee4-caf600df3669.png)
![image](https://user-images.githubusercontent.com/4289031/189112420-d7aa1be7-3055-49ed-8eba-7cc28cb9936e.png)

**Comment by dzsak** [comment]
https://github.com/amatsuda/heavens_door/issues/15#issuecomment-465780246

**Comment by laszlocph** [comment]
True, i was running Gimlet locally without https. Is there a copy implementation that basef on an another browser API?
