### ISSUE TITLE
Ability to see more commits in repository page

### ISSUE THREAD

**Issue by madss** [gimlet-io/gimlet#353]
The repository page is listing the ten most recent commits together with labels indicating where they are deployed. If the deployment is more than ten commits behind, the visibility of the deployment is lost.

Options could be
- A dropdown for choosing the amount of commits to show
- an infinite scrolling list of commits
- a paginated list of commits

**Comment by laszlocph** [comment]
Thank you, Mads. We added this to the dev queue.
