### ISSUE TITLE
Typos in your Pricing page

### ISSUE THREAD

**Issue by RobertoPrevato** [gimlet-io/gimlet#411]
Hi
I'm not a native English speaker, so no intention to be know-it-all, but I thought you might like getting this information.

You have a few typos in your Pricing page:

1. In each card there is _fearures_ instead of _features_.
2. In the third card, _business_ is not written properly. It's written with two "n" (_businness_).

![image](https://user-images.githubusercontent.com/2576032/212038235-fa7ad466-cffa-4fe8-ab6f-070d73e49f79.png)

**Comment by laszlocph** [comment]
:fearful: Much appreciated!

**Comment by laszlocph** [comment]
https://github.com/gimlet-io/gimlet-documentation/pull/13
