### ISSUE TITLE
Creating secrets code example box overflows 

### ISSUE THREAD

**Issue by Teemukoivumaa** [gimlet-io/gimlet#418]
When looking at the documentation for [Onechart reference secrets](https://gimlet.io/docs/onechart-reference#secrets) the creating secrets code example overflows when you're in fullscreen.
![kuva](https://user-images.githubusercontent.com/35847478/213873648-9bb36b55-236c-416c-9479-c1eec2aedafd.png)

After you downscale the window it will be back to normal
![kuva](https://user-images.githubusercontent.com/35847478/213873783-d5a052cb-4c91-48b8-93c7-4cd31725323e.png)

**Comment by Teemukoivumaa** [comment]
Tested in Firefox & Google Chrome

**Comment by laszlocph** [comment]
It is broken indeed. Will give it some love soonish.

Thank you for your report @Teemukoivumaa

**Comment by laszlocph** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/4289031/214038439-69f4e193-8907-43bf-a201-2007bc69057e.png)
