### ISSUE TITLE
Ability to disable kustomization per app?

### ISSUE THREAD

**Issue by whitedr** [gimlet-io/gimlet#476]
Hi there,

I just upgraded to v0.15.4 and noticed that now I'm seeing a kustomization manifest get generated for each app in the `<env>/flux` directory.  I can see the PR for this here: https://github.com/gimlet-io/gimlet/pull/459 so I know where this was introduced and have some idea of why it was added.  A couple questions though...

* Can this behavior be disabled so that I can have the (previous) default behavior of one kustomization for all apps in an env?
* How does this work with "preview" apps and specifically removal of preview apps upon branch deletion?

Being able to disable this is a higher priority for me as it's causing a lot of unneeded commits and kustomization files that I'm having to periodically cleanup.  Thanks.

**Comment by laszlocph** [comment]
Hello @whitedr 

thank you for the report, yes it is a recent change. Can I ask a few things to assess the situation?

> have some idea of why it was added
Basically it is robustness. There were too many stuck deploys and cross team issues. One app config causing an issue, clogging the deployment of other apps.

> Can this behavior be disabled 
At the moment no. But assessing the situation, we may move this under a setting.

> How does this work with "preview" apps 
Good point. I believe this change will break the cleanup. Cleanup deletes the app deployment manifests, but not the kustomization. Let us test it and adjust the behavior.

>  it's causing a lot of unneeded commits and kustomization files
Can you elaborate on the unneeded commits? The kustomization per app is only created once, then it doesn't cause new commits. Unless of course you clean it up, and it comes back every time.
Can you elaborate why the many kustomization files is an issue? We rolled this feature out for a client who has 200 apps. Granted there are many kustomizations and files, but they do their job in the background. If you look at them, of course it is a lot. Do you have another idea perhaps? We do want to solve the robustness issue that kustomization per app tries to solve.

**Comment by whitedr** [comment]
> Basically it is robustness. There were too many stuck deploys and cross team issues. One app config causing an issue, clogging the deployment of other apps.

Hmm ok.  We're just starting out (on k8s that is) so only have a couple apps at this point so this is not something we've experienced.  I wasn't aware that if you have a kustomization that targets a directory that one app config with issues would cause others in the same directory to get blocked.  

> At the moment no. But assessing the situation, we may move this under a setting.

I think having this behavior being conditionally enabled might be good as it was an unexpected change and for those of us with only a handful of apps, having one kustomization per env may still be perfectly fine.

> Good point. I believe this change will break the cleanup. Cleanup deletes the app deployment manifests, but not the kustomization. Let us test it and adjust the behavior.

Great, thanks for taking a look at this.  I think this one would be necessary so as not to have preview app kustomizations grow indefinitely and pollute the gitops-apps repo.

> Can you elaborate on the unneeded commits?

What I see in my commit log is one commit for the kustomization and then another one for the app manifests.  I guess this would be a one time thing for non-preview apps but if you have many preview apps (e.g. based on non-draft PRs), then a kustomization for each can be a lot of "noise" in the commit log (and in the repo if not cleaned up as mentioned above).

Another issue that I saw with the kustomizations that were generated is the `spec.sourceRef.name` did not match with the name of the GitRepository that I had defined during bootstrapping .  I think for format there is: `gitops-repo-<org>-<app-repo-name>-<env>`.  In my case, the org part of that name got truncated to 10 characters (our org name has 12 characters).  This meant that the per-app kustomizations were broken as generated as they didn't reference an existing GitRepository.

Thanks again for the quick reply on this one.

**Comment by laszlocph** [comment]
Thank you for feedback.

Actions we are taking:
- putting the kustomization per app behind a setting toggle that can be enabled per environment. Default to disabled.
- Test and fix preview env cleanup
- Looking into the gitrepo naming mismatch

**Comment by whitedr** [comment]
You guys are the best!  Thank you so much!

**Comment by laszlocph** [comment]
Apologies with the long delay. We now released the fix in v0.15.7

- The kustomization per app setting is behind a flag now. Off by default.
![Screenshot from 2023-05-04 10-12-21](https://user-images.githubusercontent.com/4289031/236151293-6083307d-53d9-4551-8341-d2e822ee3ecb.png)
- For existing environments, the setting is true, with now easy path to turn it off. To do it:
  -  Run the following SQL update: `update environments set kustomization_per_app=true where name='xx';`
  - Clean up the gitops repository by removing all kustomizations per app files, and update the folder from `./flux` to `./` in the flux folder main kustomization. Be aware that deleting a kustomization will delete your deployments as well. Use this technique to avoid it: https://fluxcd.io/flux/faq/#how-can-i-safely-rename-a-flux-kustomization
- Also addressed the preview app cleanup worker as well. Should also clean kustomizations per app files.
