### ISSUE TITLE
Remove github.com/franela/goblin from the codebase

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet#502]
We should use only idiomatic go testing code.

**Comment by laszlocph** [comment]
This is a good first issue as
- it only requires golang knowledge and 
- only touches unit tests
- no project knowledge is required

**Comment by imharyohm** [comment]
Assign me this issue, I m new comer to open source and help me out to understand it.

**Comment by laszlocph** [comment]
Hello @imharyohm happy to have you!

In short:
- We have tests using the mentioned dependency, like in this file: https://github.com/gimlet-io/gimlet/blob/df2f475bb47fc49ea675cd8e077313cef4953e5a/pkg/commands/stack/lint_test.go#L10
```
...
g.Describe("stack lint", func() {
		g.It("Should parse a stack file", func() {
...
```
- We just want to use the built in tooling in golang for tests.
Like in here: https://github.com/gimlet-io/gimlet/blob/df2f475bb47fc49ea675cd8e077313cef4953e5a/pkg/gitops/bootstrap_test.go#L12
- The goal is to rewrite all our tests to use the plain golang testing approach.

**Comment by imharyohm** [comment]
I did the given work and make pull request ,  could you please look at once.
