### ISSUE TITLE
.sourceignore should always go to the root of the repository

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet#56]
`stack generate` puts a `.sourceignore` file next to `stack.yaml`

Flux wants `.sourceignore` in the root of the repository. This puts manual work on the end user as she has to fix it after `stack generate` if her `stack.yaml` is in a subfolder.

We may need to generate a `kustomization.yaml` as we know the files we want to apply. That way we don't need a `.sourceignore` https://fluxcd.io/docs/components/kustomize/kustomization/#generate-kustomizationyaml

**Comment by szabogabor91** [comment]
Flux is able to handle sourceignore in any folder. No need to change anything.
