### ISSUE TITLE
chore: update to Flux v2.2.0

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet#760]
ref: https://github.com/fluxcd/flux2/releases/tag/v2.2.0

- Bump go.mod dependency
- Bump `HelmRelease` kinds to `v2beta2`
  - Gimlet Stack
  - `gimlet gitops bootstrap`
  - Anywhere we create HelmReleases
- The [Alert](https://fluxcd.io/flux/components/notification/alerts/) and [Provider](https://fluxcd.io/flux/components/notification/providers/) kinds were promoted from v1beta2 to v1beta3.

**Comment by dzsak** [comment]
https://github.com/gimlet-io/gimlet-stack-reference/pull/60
