### ISSUE TITLE
feat: Policy based releases without CI integration

### ISSUE THREAD

**Issue by Phault** [gimlet-io/gimlet#764]
Policy based releases with `push` as deploy event and `main` as branch filter, does not actually deploy anything when the main branch is pushed. Setting it to `*` or `!anything-even-main` does however work. 

Also tried:

- refs/heads/main
- origin/main

To no success.

**Comment by laszlocph** [comment]
We have some unit test on this area (https://github.com/gimlet-io/gimlet/blob/main/pkg/dashboard/worker/gitops_test.go#L237-L245), and they pass, so the problem may be in the data that is passed to these functions.

Can you look at your CI step?
It prints all the information that is shipped to Gimlet, (like here: https://github.com/gimlet-io/github-actions-integration-sample/actions/runs/6495473335/job/17640515213#step:4:27)

```
  "version": {
...
    "branch": "shipper-test",
...
  },
```

Other things to cross-check is the `app` and `env` fields in the Gimlet manifest, like this one: https://github.com/gimlet-io/github-actions-integration-sample/blob/main/.gimlet/staging-gais.yaml#L1-L2

If branch is matching, but the env does not exist, there won't be a deploy.

**Comment by Phault** [comment]
I haven't added any CI step to the project in question. It's simply a fork of https://github.com/gimlet-io/reactjs-test-app configured in Gimlet with the static site template. So I'm assuming it relies on webhooks to trigger the releases. I should probably mention I'm using your hosted version of Gimlet, so the webhooks themselves should be working fine.

I've double-checked the mentioned `app` and `env` fields, which appear correct.

**Comment by laszlocph** [comment]
> I haven't added any CI step to the project in question

Ah okay. This adds up then. Policies only trigger with the CI step.

Let me rename this issue and let us address this. This is a hole in the behavior.
