### ISSUE TITLE
Branch delete event not detecting deleted branches

### ISSUE THREAD

**Issue by whitedr** [gimlet-io/gimlet#784]
I have been trying to get preview app auto cleanup policy working as documented here: https://gimlet.io/docs/how-to-configure-preview-environments#cleaning-up-preview-apps

I have the following policy/cleanup defined in a "prevew" manifest:

```
deploy:
  event: pr
cleanup:
  branch: "*"
  event: branchDeleted
  app: lego-{{ .BRANCH | sanitizeDNSName }}
```

but I'm never seeing gimlet dashboard actually detect and cleanup the preview apps from our gitops-apps repo.  I can confirm that I have the GitHub app integration working correctly as I see the events getting sent from there and handled ok in gimlet-dashboard.

Upon digging through the code a bit I think I may have spotted the issue.  It looks like in this worker here: https://github.com/gimlet-io/gimlet/blob/cd6798fe56fc176756de8211cddb9d78cb170439/pkg/dashboard/worker/branchDeleteEvent.go#L132 it is trying to detect deleted branches by comparing the local set of cached remote branches with the origin (GitHub) and grabbing those that are no longer there as "deleted" branches.  However, over here in repoCache worker: https://github.com/gimlet-io/gimlet/blob/main/pkg/git/nativeGit/repoCache.go#L159 it is also doing a fetch regularly (e.g. upon detecting the repo cache is invalidated) which I think may be pruning the deleted branches before the branchDeleteEvent worker has a chance to detect the branch is deleted.

This is just my theory based on looking at the code and I could be completely wrong and missing something but any insight you might provide and whether I may be on to something with my theory would be greatly appreciated.  Thanks!

**Comment by laszlocph** [comment]
Stellar analysis! Please allow us a couple of days to analyse this.

**Comment by laszlocph** [comment]
`gimlet-v0.25.0-rc.1` has a potential fix.
