### ISSUE TITLE
feat: Add ability to set imagePullSecrets from the GUI

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet#793]
https://github.com/gimlet-io/onechart/blob/933a10bc84c9446f910f0a961e2ed36556122842/website/docs/examples/deploying-a-private-image.md?plain=1#L8

**Comment by dzsak** [comment]
https://github.com/gimlet-io/onechart/pull/115

**Comment by laszlocph** [comment]
https://github.com/gimlet-io/gimlet/commit/c92befd7bb4041aeb022e248ef28337c7ff68d20
