### ISSUE TITLE
Make gimlet less dependent on GitHub

### ISSUE THREAD

**Issue by LoicGombeaud** [gimlet-io/gimlet#99]
Hi Laszlo, I've been testing gimlet over the last few days, and I'm really impressed by what you've achieved. I think your project has the potential to become the new standard to easily deploy applications to Kubernetes: it's modular, with a sound architecture that you can pick and choose from, and it makes sane assumptions about what a developer would want to deploy - I love it.

I've noticed one drawback for the moment: it seems to be very dependent on GitHub; for instance:
- `gimletd` is [hard-coded](https://github.com/gimlet-io/gimlet/blob/main/pkg/gimletd/git/nativeGit/helper.go#L26) to only work with a GitOps repo hosted on GitHub, although it doesn't use any specific GitHub capabilities (as far as I can see)
- `dashboard` uses a GitHub application to access the GitOps repo; I haven't checked out the code, but it seems to only access the git commits, which could also be achieved with SSH/HTTPS access to the repo?

If this barrier was lifted, it would help users like who use GitLab (or other services).

**Comment by laszlocph** [comment]
@LoicAG appreciate your message.

It is a deliberate choice to do only Github for now. We would like to go deep in certain communities, then go wide when we have traction and bandwidth to do other git providers.

**Comment by louisschprs** [comment]
Hi Laszlo, we also prefer to use Gitlab over Github and I believe it would be beneficial to get this to work with BitBucket in the future as well.

**Comment by laszlocph** [comment]
Hoping to deliver this within this calendar year.

**Comment by laszlocph** [comment]
Now the installer and Gimlet supports Gitlab.
This is an alpha release, so feedback is much appreciated.

Install Gimlet on a local cluster to test it out: 
https://gimlet.io/docs/installation
